name: check-auditd-rules

# Tests the latest auditd rules file for errors.
# Need to try using docker on runner to test fedora, debian, etc

on:
  push:
    branches:
      - testing
defaults:
  run:
    shell: bash
jobs:
  check-auditd-rules:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: testing
      - name: Update package information
        run: sudo apt update
      - name: Install auditd
        run: sudo apt install -y auditd
      - name: Start auditd
        run: if ! (systemctl is-active auditd); then sudo systemctl start auditd; fi
      - name: Copy rules file to rules directory
        run: sudo cp $GITHUB_WORKSPACE/40-mitre.rules /etc/audit/rules.d/
      - name: Remove default rules
        run: if sudo [ -e /etc/audit/rules.d/audit.rules ]; then sudo rm /etc/audit/rules.d/audit.rules; fi
      - name: Check rules
        run: sudo augenrules --check 2>&1
      - name: Load rules
        run: sudo augenrules --load 2>&1
